<?php
namespace App\Services;
use \App\Exceptions\AppException;

class Halt
{
    const ERRORS = [
        // 1000 app
        1000 => 'app error',
        1001 => 'wait a bit',

        // 1100 user
        1101 => 'user not found',
        1102 => 'user action denied',
        1103 => 'user limit exceeded',
        1104 => 'create_date is empty',
        1105 => 'create_date is incorrect',
        1106 => 'update_date is empty',
        1107 => 'update_date is incorrect',
        1108 => 'remind_date is empty',
        1109 => 'remind_date is incorrect',
        1110 => 'user_status is empty',
        1111 => 'user_status is incorrect',
        1112 => 'user_status is trash',
        1113 => 'user_token is empty',
        1114 => 'user_token is incorrect',
        1115 => 'user_token is occupied',
        1116 => 'user_hash is incorrect',
        1117 => 'user_hash expired',
        1118 => 'user_email is empty',
        1119 => 'user_email is incorrect',
        1120 => 'user_email is occupied',
        1121 => 'user_name is empty',
        1122 => 'user_name is incorrect',
        1123 => 'user_timezone is empty',
        1124 => 'user_timezone is incorrect',

        // 1200 user term
        1201 => 'term not found',
        1202 => 'term action denied',
        1203 => 'term limit exceeded',
        1204 => 'create_date is empty',
        1205 => 'create_date is incorrect',
        1206 => 'update_date is empty',
        1207 => 'update_date is incorrect',
        1208 => 'user_id is empty',
        1209 => 'user_id is incorrect',
        1210 => 'term_key is empty',
        1211 => 'term_key is incorrect',
        1212 => 'term_value is empty',
        1213 => 'term_value is incorrect',

        // 1300 billing
        1301 => 'billing not found',
        1302 => 'billing action denied',
        1303 => 'billing limit exceeded',
        1304 => 'create_date is empty',
        1305 => 'create_date is incorrect',
        1306 => 'update_date is empty',
        1307 => 'update_date is incorrect',
        1308 => 'expires_date is empty',
        1309 => 'expires_date is incorrect',
        1310 => 'user_id is incorrect',
        1311 => 'space_size is empty',
        1312 => 'space_size is incorrect',
        1313 => 'space_interval is empty',
        1314 => 'space_interval is incorrect',
        1315 => 'billing_status is empty',
        1316 => 'billing_status is incorrect',
        1317 => 'billing_code is empty',
        1318 => 'billing_code is incorrect',
        1319 => 'billing_sum is empty',
        1320 => 'billing_sum is incorrect',
        1321 => 'billing_currency is empty',
        1322 => 'billing_currency is incorrect',
        1323 => 'billing_comment is incorrect',

        // 1400 user role
        1401 => 'role not found',
        1402 => 'role action denied',
        1403 => 'role limit exceeded',
        1404 => 'create_date is empty',
        1405 => 'create_date is incorrect',
        1406 => 'update_date is empty',
        1407 => 'update_date is incorrect',
        1408 => 'user_id is empty',
        1409 => 'user_id is incorrect',
        1410 => 'repo_id is empty',
        1411 => 'repo_id is incorrect',
        1412 => 'role_status is empty',
        1413 => 'role_status is incorrect',

        // 1500 repo
        1501 => 'repo not found',
        1502 => 'repo action denied',
        1503 => 'repo limit exceeded',
        1504 => 'create_date is empty',
        1505 => 'create_date is incorrect',
        1506 => 'update_date is empty',
        1507 => 'update_date is incorrect',
        1508 => 'user_id is empty',
        1509 => 'user_id is incorrect',
        1510 => 'repo_name is empty',
        1511 => 'repo_name is incorrect',

        // 1600 repo term
        1601 => 'term not found',
        1602 => 'term action denied',
        1603 => 'term limit exceeded',
        1604 => 'create_date is empty',
        1605 => 'create_date is incorrect',
        1606 => 'update_date is empty',
        1607 => 'update_date is incorrect',
        1608 => 'repo_id is empty',
        1609 => 'repo_id is incorrect',
        1610 => 'term_key is empty',
        1611 => 'term_key is incorrect',
        1612 => 'term_value is empty',
        1613 => 'term_value is incorrect',

        // 1700 post
        1701 => 'post not found',
        1702 => 'post action denied',
        1703 => 'post limit exceeded',
        1704 => 'create_date is empty',
        1705 => 'create_date is incorrect',
        1706 => 'update_date is empty',
        1707 => 'update_date is incorrect',
        1708 => 'user_id is empty',
        1709 => 'user_id is incorrect',
        1710 => 'repo_id is empty',
        1711 => 'repo_id is incorrect',
        1712 => 'post_status is empty',
        1713 => 'post_status is incorrect',
        1714 => 'post_status is trash',
        1715 => 'post_title is empty',
        1716 => 'post_title is incorrect',

        // 1800 post term
        1801 => 'term not found',
        1802 => 'term action denied',
        1803 => 'term limit exceeded',
        1804 => 'create_date is empty',
        1805 => 'create_date is incorrect',
        1806 => 'update_date is empty',
        1807 => 'update_date is incorrect',
        1808 => 'post_id is empty',
        1809 => 'post_id is incorrect',
        1810 => 'term_key is empty',
        1811 => 'term_key is incorrect',
        1812 => 'term_value is empty',
        1813 => 'term_value is incorrect',

        // 1900 post tag
        1901 => 'tag not found',
        1902 => 'tag action denied',
        1903 => 'tag limit exceeded',
        1904 => 'create_date is empty',
        1905 => 'create_date is incorrect',
        1906 => 'update_date is empty',
        1907 => 'update_date is incorrect',
        1908 => 'post_id is empty',
        1909 => 'post_id is incorrect',
        1910 => 'tag_value is empty',
        1911 => 'tag_value is incorrect',

        // 2000 comment
        2001 => 'comment not found',
        2002 => 'comment action denied',
        2003 => 'comment limit exceeded',
        2004 => 'create_date is empty',
        2005 => 'create_date is incorrect',
        2006 => 'update_date is empty',
        2007 => 'update_date is incorrect',
        2008 => 'user_id is empty',
        2009 => 'user_id is incorrect',
        2010 => 'post_id is empty',
        2011 => 'post_id is incorrect',
        2012 => 'comment_content is empty',
        2013 => 'comment_content is incorrect',

        // 2100 upload
        2101 => 'upload not found',
        2102 => 'upload action denied',
        2103 => 'upload limit exceeded',
        2104 => 'create_date is empty',
        2105 => 'create_date is incorrect',
        2106 => 'update_date is empty',
        2107 => 'update_date is incorrect',
        2108 => 'user_id is empty',
        2109 => 'user_id is incorrect',
        2110 => 'comment_id is empty',
        2111 => 'comment_id is incorrect',
        2112 => 'upload_name is empty',
        2113 => 'upload_name is incorrect',
        2114 => 'upload_file is empty',
        2115 => 'upload_file is incorrect',
        2116 => 'upload_file is occupied',
        2117 => 'upload_mime is empty',
        2118 => 'upload_mime is incorrect',
        2119 => 'upload_size is empty',
        2120 => 'upload_size is incorrect',
        2121 => 'thumb_file is incorrect',
        2122 => 'thumb_file is occupied',
        2123 => 'directory make failed',
        2124 => 'directory delete failed',
        2125 => 'file read failed',
        2126 => 'file write failed',
        2127 => 'file delete failed',
        2128 => 'file MIME type is incorrect',
        2129 => 'file size is too large',

        // 2200 alert
        2201 => 'alert not found',
        2202 => 'alert action denied',
        2203 => 'alert limit exceeded',
        2204 => 'create_date is empty',
        2205 => 'create_date is incorrect',
        2206 => 'update_date is empty',
        2207 => 'update_date is incorrect',
        2208 => 'user_id is empty',
        2209 => 'user_id is incorrect',
        2210 => 'repo_id is empty',
        2211 => 'repo_id is incorrect',
        2212 => 'post_id is empty',
        2213 => 'post_id is incorrect',
        2214 => 'comment_id is empty',
        2215 => 'comment_id is incorrect',

    ];

    public static function throw(int $code) {
        $message = array_key_exists($code, self::ERRORS) ? self::ERRORS[$code] : self::ERRORS[1000];
        throw new AppException($message, $code);
    }

}
